language: r
warnings_are_errors: false
cache:
  packages: true
before_install:
  - bash configure.sh
script:
  - Rscript -e "rmarkdown::render_site()"
deploy:
  - provider: pages
    skip_cleanup: true
    local-dir: _site/
    github-token: $GITHUB_TOKEN
    on:
      branch: master
notifications:
  email: false
